### PR TITLE
Don't prefix robot links with robot if already in the name

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by Rayman** [comment]
Is this fix resulting from a bug? What does it solve?

**Comment by MatthijsBurgh** [comment]
I was annoyed by the sergio labels in rviz. These are comming from ed. This is one of the steps to fix it.

**Comment by MatthijsBurgh** [comment]
Relates to https://github.com/tue-robotics/ed_gui_server/pull/15

**Comment by alberth** [comment]
Seems to me that lack of a proper description for the variables is the root cause. Adding work-arounds in the form of ad-hoc automagic corrections just adds to the confusion, and more ad-hoc fixes.

**Pull request merged**
