### PR TITLE
Rwc2019

### PR DESCRIPTION
**Pull request by PetervDooren**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@jlunenburg do you agree with the changes, then it can be merged.

**Comment by jlunenburg** [comment]
> @jlunenburg do you agree with the changes, then it can be merged.

Quite frankly, I don't know; kind of miss context: in both cases, I don't know why the change was required ;-)

**Comment by MatthijsBurgh** [comment]
I reverted the switch of adding and removing the flags. The kinect plugin, requested to remove a flag to all entities, even if the entity didn't have the flag, because one entity would also have that same flag added again. I added a check in the kinect plugin, so the old order of removing and adding should also work with the kinect plugin.

**Comment by MatthijsBurgh** [comment]
Also approved by @PetervDooren

**Pull request merged**
